version: 2.1

jobs:
  test:
    docker:
      - image: cimg/rust:1.65.0
    resource_class: small
    steps:
      - checkout
      - run: cargo --version
      - run:
          name: Run Tests
          command: cargo test
  build-arm64:
    machine:
      image: ubuntu-2204:2022.10.2
    resource_class: arm.medium
    steps:
      - checkout
      - run: docker login -u "$DOCKERHUB_USER_NAME" -p "$DOCKERHUB_ACCESS_TOKEN"
      - run: |
          docker buildx build --push --tag ${DOCKERHUB_CONTAINER_NAMESPACE}/app-manager:${CIRCLE_TAG:-$CIRCLE_BRANCH}-arm64 .
  build-amd64:
    docker:
      - image: cimg/base:2023.01
    resource_class: medium
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.18
          docker_layer_caching: true
      - run: docker login -u "$DOCKERHUB_USER_NAME" -p "$DOCKERHUB_ACCESS_TOKEN"
      - run: |
          docker buildx build --push --tag ${DOCKERHUB_CONTAINER_NAMESPACE}/app-manager:${CIRCLE_TAG:-$CIRCLE_BRANCH}-amd64 .
  push:
    docker:
      - image: cimg/base:2023.01
    resource_class: small
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.18
          docker_layer_caching: true
      - run: docker login -u "$DOCKERHUB_USER_NAME" -p "$DOCKERHUB_ACCESS_TOKEN"
      - run: ./create-manifest.sh ${DOCKERHUB_CONTAINER_NAMESPACE}/app-manager "${CIRCLE_TAG:-$CIRCLE_BRANCH}"

workflows:
  docker-deployment:
    jobs:
      - build-amd64:
          context:
            - Docker builds
          filters:
            tags:
              only: /^v.*/
            branches:
              only: /.*/
      - build-arm64:
          context:
            - Docker builds
          filters:
            tags:
              only: /^v.*/
            branches:
              only: /.*/
      - test:
          filters:
            tags:
              only: /^v.*/
            branches:
              only: /.*/
      - push:
          requires:
            - build-amd64
            - build-arm64
            - test
          context:
            - Docker builds
          filters:
            tags:
              only: /^v.*/
            branches:
              only: /.*/